# Generated by Django 5.1 on 2024-08-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_organizers',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Организатор'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_presence',
            field=models.BooleanField(default=False, verbose_name='Присутствие'),
            preserve_default=False,
        ),
    ]
