# Generated by Django 5.1 on 2024-08-14 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255, verbose_name='Имя события')),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время события')),
                ('event_location', models.CharField(max_length=255, verbose_name='Место события')),
            ],
            options={
                'verbose_name': 'Постер события',
                'verbose_name_plural': 'Постеры событий',
                'ordering': ['event_time'],
            },
        ),
    ]
