# Generated by Django 5.1 on 2024-08-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='event_day',
            field=models.CharField(default=2, max_length=50, verbose_name='День события'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poster',
            name='event_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место события'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='event_time',
            field=models.TimeField(verbose_name='Время события'),
        ),
    ]
