# Generated by Django 4.2 on 2024-08-15 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/', verbose_name='Медиафайл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Медиафайл',
                'verbose_name_plural': 'Медиафайлы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
